#!/usr/bin/env python3
"""
MIMIR F1 Driver Rating Model — FastF1 collector (v1).

Minimal, one-shot export script: takes a season/round/driver list, pulls Qualifying + Race
session data from FastF1's local cache (downloading on first run), and writes a single JSON
file matching the `fastf1-export-v1` schema documented in
backend/src/f1rating/adapters/fastF1Adapter.ts (race laps) and
backend/src/f1rating/adapters/jolpicaAdapter.ts (qualifying segment times).

Usage:
    .venv/bin/python3 collect.py --season 2025 --round 1 --drivers NOR,PIA

Writes output/{season}_{round}.json and exits. No server, no watcher, no long-running process.

`output/{season}_{round}.json` files ARE committed — they are RECORDED CALIBRATION INPUTS (real
FastF1 data, stable/reproducible byte-for-byte given the same FastF1 data release), not scratch
output. `output/calibration-report.json` is the opposite: it's regenerated by
`npm run f1rating:calibrate` (backend/) FROM those recorded inputs, carries a live `generatedAt`
timestamp, and is gitignored — run the calibrate script locally to reproduce it on demand.

WHAT THIS DOES NOT DO
----------------------
- Does not classify DNFs as driver-attributable vs technical, or flag damaged-car laps —
  those require human review per the engine's data-quality invariants (see types.ts doc
  comments) and are intentionally left to the TypeScript side / manual review layer.
- Does not compute trackCondition with sub-lap precision — it takes the nearest weather
  sample's Rainfall flag to each lap's start time, which is a per-lap approximation, not a
  guarantee that conditions were uniform across the whole lap.
"""
import argparse
import json
import sys
from pathlib import Path

import fastf1
import pandas as pd

SCHEMA_VERSION = "fastf1-export-v1"

COMPOUND_MAP = {
    "SOFT": "soft", "MEDIUM": "medium", "HARD": "hard",
    "INTERMEDIATE": "intermediate", "WET": "wet",
}


def map_compound(raw: str) -> str:
    if raw in COMPOUND_MAP:
        return COMPOUND_MAP[raw]
    print(f"warning: unknown compound '{raw}', defaulting to 'medium'", file=sys.stderr)
    return "medium"


def map_track_status(raw: str) -> str:
    digits = str(raw) if raw is not None else ""
    if "5" in digits:
        return "red"
    if "4" in digits:
        return "sc"
    if "6" in digits or "7" in digits:
        return "vsc"
    return "green"


def ms(td) -> int | None:
    if td is None or pd.isna(td):
        return None
    return int(td.total_seconds() * 1000)


def format_ergast_time(td) -> str | None:
    """mm:ss.SSS, matching the Ergast/Jolpica Q1/Q2/Q3 string format jolpicaAdapter.ts parses."""
    if td is None or pd.isna(td):
        return None
    total_ms = int(td.total_seconds() * 1000)
    minutes, rem_ms = divmod(total_ms, 60_000)
    seconds, millis = divmod(rem_ms, 1000)
    return f"{minutes}:{seconds:02d}.{millis:03d}"


def nearest_rainfall(weather: pd.DataFrame, lap_time) -> bool:
    if pd.isna(lap_time) or weather.empty:
        return False
    idx = (weather["Time"] - lap_time).abs().idxmin()
    return bool(weather.loc[idx, "Rainfall"])


def collect_qualifying(season: int, round_no: int, driver_codes: list[str]) -> list[dict]:
    session = fastf1.get_session(season, round_no, "Q")
    session.load(laps=False, telemetry=False, weather=False, messages=False)
    results = session.results
    out = []
    for code in driver_codes:
        row = results[results["Abbreviation"] == code]
        if row.empty:
            print(f"warning: driver {code} not found in Q results for {season} round {round_no}", file=sys.stderr)
            continue
        r = row.iloc[0]
        out.append({
            "driverId": r["DriverId"],
            "constructorId": r["TeamId"],
            # Jolpica/Ergast-style contract expects position as a string (JolpicaQualifyingResult.position).
            "position": str(int(r["Position"])) if pd.notna(r["Position"]) else None,
            "Q1": format_ergast_time(r["Q1"]),
            "Q2": format_ergast_time(r["Q2"]),
            "Q3": format_ergast_time(r["Q3"]),
        })
    return out


def collect_race(season: int, round_no: int, driver_codes: list[str]) -> list[dict]:
    session = fastf1.get_session(season, round_no, "R")
    session.load(laps=True, telemetry=False, weather=True, messages=False)
    results = session.results
    weather = session.weather_data

    out = []
    for code in driver_codes:
        result_row = results[results["Abbreviation"] == code]
        if result_row.empty:
            print(f"warning: driver {code} not found in R results for {season} round {round_no}", file=sys.stderr)
            continue
        r = result_row.iloc[0]

        driver_laps = session.laps.pick_drivers(code).sort_values("LapNumber")
        laps_out = []
        for _, lap in driver_laps.iterrows():
            laps_out.append({
                "lapNumber": int(lap["LapNumber"]),
                "lapTimeMs": ms(lap["LapTime"]),
                "compound": map_compound(lap["Compound"]),
                "tyreLifeLaps": int(lap["TyreLife"]) if pd.notna(lap["TyreLife"]) else 0,
                "stintNumber": int(lap["Stint"]) if pd.notna(lap["Stint"]) else 1,
                "trackStatus": map_track_status(lap["TrackStatus"]),
                "trackCondition": "wet" if nearest_rainfall(weather, lap["LapStartTime"]) else "dry",
                "isPitOutLap": bool(pd.notna(lap["PitOutTime"])),
                "isPitInLap": bool(pd.notna(lap["PitInTime"])),
                "isAccurate": bool(lap["IsAccurate"]),
                "isDamaged": False,
                "position": int(lap["Position"]) if pd.notna(lap["Position"]) else None,
            })

        out.append({
            "schemaVersion": SCHEMA_VERSION,
            "season": season,
            "round": round_no,
            "sessionType": "Race",
            "driverId": r["DriverId"],
            "constructorId": r["TeamId"],
            "gridPosition": int(r["GridPosition"]) if pd.notna(r["GridPosition"]) else None,
            "finishPosition": int(r["Position"]) if pd.notna(r["Position"]) else None,
            "classified": r["Status"] == "Finished" or str(r["Status"]).startswith("+"),
            "status": r["Status"],
            "laps": laps_out,
        })
    return out


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="MIMIR F1 rating — FastF1 collector")
    parser.add_argument("--season", type=int, required=True)
    parser.add_argument("--round", type=int, required=True)
    parser.add_argument("--drivers", type=str, required=True, help="Comma-separated FastF1 driver codes, e.g. NOR,PIA")
    parser.add_argument("--cache", type=str, default="cache")
    parser.add_argument("--out", type=str, default="output")
    return parser


def parse_driver_codes(raw: str) -> list[str]:
    return [c.strip().upper() for c in raw.split(",") if c.strip()]


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    driver_codes = parse_driver_codes(args.drivers)

    cache_dir = Path(args.cache)
    cache_dir.mkdir(parents=True, exist_ok=True)
    fastf1.Cache.enable_cache(str(cache_dir))

    print(f"Collecting season={args.season} round={args.round} drivers={driver_codes}...", file=sys.stderr)
    qualifying = collect_qualifying(args.season, args.round, driver_codes)
    race = collect_race(args.season, args.round, driver_codes)

    payload = {
        "schemaVersion": SCHEMA_VERSION,
        "season": args.season,
        "round": args.round,
        "qualifying": qualifying,
        "race": race,
    }

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{args.season}_{args.round:02d}.json"
    out_path.write_text(json.dumps(payload, indent=2))
    print(f"Wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
