import type { AchievementDef, AchievementCategory } from './types'

export const CATEGORY_LABEL: Record<AchievementCategory, string> = {
  memory:    "ПАМ'ЯТЬ",
  spaces:    'ПРОСТОРИ',
  finance:   'ФІНАНСИ',
  sprint:    'СПРИНТ',
  watchlist: 'МЕДІА',
}

/** Category select icon on the well home screen — public/achivement/category/*.webp */
export const CATEGORY_ICON: Record<AchievementCategory, string> = {
  memory:    '/achivement/category/memory.png',
  spaces:    '/achivement/category/space.png',
  finance:   '/achivement/category/finance.png',
  sprint:    '/achivement/category/sprint.png',
  watchlist: '/achivement/category/media.png',
}

/** Branch shown after selecting a category — public/achivement/category-well/*.png */
export const CATEGORY_WELL_BG: Record<AchievementCategory, string> = {
  memory:    '/achivement/category-well/memory.png',
  spaces:    '/achivement/category-well/spaces.png',
  finance:   '/achivement/category-well/finance.png',
  sprint:    '/achivement/category-well/sprint.png',
  watchlist: '/achivement/category-well/media.png',
}

/**
 * "Повернутись до дерева" button position (% of canvas) — the glowing floor
 * sigil beneath the roots. Same spot in all 5 branch renders (shared template),
 * so unlike the old well-mouth this is a single constant, not per-category.
 */
export const TREE_RETURN_POS = { x: 12, y: 6 }

export const ACHIEVEMENT_DEFS: AchievementDef[] = [
  // ── ПАМʼЯТЬ (10) ───────────────────────────────────────────────────────────
  {
    id: 'first-memory',
    category: 'memory',
    title: 'ПЕРШИЙ СПОГАД',
    description: 'Додай свій перший спогад.',
    flavor: 'Ти залишив перший слід у криниці.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᚠ',
  },
  {
    id: 'memory-with-photo',
    category: 'memory',
    title: 'СПОГАД З ОБРАЗОМ',
    description: 'Додай спогад із фото.',
    flavor: 'Не все треба пояснювати словами.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚢ',
  },
  {
    id: 'past-memory',
    category: 'memory',
    title: 'ПОВЕРНЕНЕ МИНУЛЕ',
    description: 'Додай спогад із датою в минулому.',
    flavor: 'Те, що минуло, ще не зникло.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚦ',
  },
  {
    id: 'three-memories',
    category: 'memory',
    title: 'ТРИ СПОГАДИ',
    description: 'Додай 3 спогади.',
    flavor: 'Три — це вже не випадковість.',
    target: 3,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚨ',
  },
  {
    id: 'ten-memories',
    category: 'memory',
    title: 'ДЕСЯТЬ СЛІДІВ',
    description: 'Додай 10 спогадів.',
    flavor: 'Криниця наповнюється.',
    target: 10,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚱ',
  },
  {
    id: 'seven-days-memory',
    category: 'memory',
    title: 'СІМ ДНІВ ПАМʼЯТІ',
    description: 'Додай спогади у 7 різних днів.',
    flavor: 'Памʼять не любить поспіх. Вона любить повернення.',
    target: 7,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚲ',
  },
  {
    id: 'month-memory',
    category: 'memory',
    title: 'МІСЯЦЬ НЕ ЗНИК',
    description: 'Додай спогади у 20 різних днів.',
    flavor: 'Місяць, що залишив сліди. Це рідкість.',
    target: 20,
    reward: 30,
    rarity: 'stone',
    rune: 'ᚷ',
  },
  {
    id: 'memory-in-space',
    category: 'memory',
    title: 'СПОГАД У ПРОСТОРІ',
    description: 'Привʼяжи спогад до простору.',
    flavor: 'Місце і момент. Тепер вони звʼязані.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚹ',
  },
  {
    id: 'memory-with-person',
    category: 'memory',
    title: 'СПОГАД З ЛЮДИНОЮ',
    description: 'Додай людину до спогаду.',
    flavor: 'Памʼять стає спільною — і тому сильнішою.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚺ',
  },
  {
    id: 'archive-25',
    category: 'memory',
    title: 'АРХІВ ПРОКИНУВСЯ',
    description: 'Створи 25 спогадів.',
    flavor: 'Криниця вже не порожня. Вона говорить.',
    target: 25,
    reward: 50,
    rarity: 'root',
    rune: 'ᚾ',
  },

  // ── ПРОСТОРИ (10) ──────────────────────────────────────────────────────────
  {
    id: 'first-space',
    category: 'spaces',
    title: 'ПЕРШИЙ ПРОСТІР',
    description: 'Створи свій перший простір.',
    flavor: 'У хаосу зʼявилась кімната.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛁ',
  },
  {
    id: 'space-with-profile',
    category: 'spaces',
    title: 'ОПИСАНИЙ ПРОСТІР',
    description: 'Заповни профіль простору (авто, дім, тварина або подорож).',
    flavor: 'Місце отримало характер. Тепер воно — не просто назва.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛃ',
  },
  {
    id: 'space-with-cover',
    category: 'spaces',
    title: 'ОБКЛАДИНКА МІСЦЯ',
    description: 'Додай обкладинку до простору.',
    flavor: 'Місце отримало своє обличчя. Тепер його не сплутаєш.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛇ',
  },
  {
    id: 'three-spaces',
    category: 'spaces',
    title: 'ТРИ ПРОСТОРИ',
    description: 'Створи 3 простори.',
    flavor: 'Твоя карта починає мати форму.',
    target: 3,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛈ',
  },
  {
    id: 'five-spaces',
    category: 'spaces',
    title: 'ПʼЯТЬ ПРОСТОРІВ',
    description: 'Створи 5 просторів.',
    flavor: 'Пʼять кімнат. Місце стало картою.',
    target: 5,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛉ',
  },
  {
    id: 'living-space',
    category: 'spaces',
    title: 'ЖИВИЙ ПРОСТІР',
    description: 'Додай 3 спогади в один простір.',
    flavor: 'Простір оживає, коли в ньому щось відбувається.',
    target: 3,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛊ',
  },
  {
    id: 'full-space',
    category: 'spaces',
    title: 'НАСЕЛЕНИЙ ПРОСТІР',
    description: 'Додай 10 спогадів в один простір.',
    flavor: 'Не місце для спогадів. Місце зі спогадами.',
    target: 10,
    reward: 30,
    rarity: 'stone',
    rune: 'ᛏ',
  },
  {
    id: 'first-auto',
    category: 'spaces',
    title: 'АВТОСЛІД',
    description: 'Створи простір типу «Авто».',
    flavor: 'Навіть машина має памʼять. І рахунки.',
    target: 1,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛒ',
    hidden: true,
  },
  {
    id: 'first-pet',
    category: 'spaces',
    title: 'ВІРНИЙ СУПУТНИК',
    description: 'Створи простір типу «Вихованець».',
    flavor: 'Хтось чекає на тебе вдома. І памʼятає теж.',
    target: 1,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛖ',
    hidden: true,
  },
  {
    id: 'life-map',
    category: 'spaces',
    title: 'КАРТА ЖИТТЯ',
    description: 'Створи простори щонайменше 5 різних типів.',
    flavor: 'Ти не просто організував. Ти намалював карту.',
    target: 5,
    reward: 50,
    rarity: 'root',
    rune: 'ᛗ',
  },

  // ── ФІНАНСИ (10) ───────────────────────────────────────────────────────────
  {
    id: 'first-transaction',
    category: 'finance',
    title: 'ПЕРША МОНЕТА',
    description: 'Додай перший фінансовий запис.',
    flavor: 'Одна монета — теж початок криниці.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛚ',
  },
  {
    id: 'seven-records',
    category: 'finance',
    title: 'СІМ ЗАПИСІВ',
    description: 'Додай 7 фінансових записів.',
    flavor: 'Патерни зʼявляються там, де є сліди.',
    target: 7,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛜ',
  },
  {
    id: 'ten-records',
    category: 'finance',
    title: 'ДЕСЯТЬ МОНЕТ',
    description: 'Додай 10 фінансових записів.',
    flavor: 'Десять слідів — і туман вже не такий густий.',
    target: 10,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛞ',
  },
  {
    id: 'no-fog-day',
    category: 'finance',
    title: 'ДЕНЬ БЕЗ ТУМАНУ',
    description: 'Запиши витрати за один день.',
    flavor: 'День став видимим.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛟ',
  },
  {
    id: 'week-watched',
    category: 'finance',
    title: 'ТИЖДЕНЬ ПІД НАГЛЯДОМ',
    description: 'Додай записи у 7 різних днів.',
    flavor: 'Сім днів без туману. Ти вже бачиш.',
    target: 7,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚠ',
  },
  {
    id: 'month-watched',
    category: 'finance',
    title: 'МІСЯЦЬ ПІД НАГЛЯДОМ',
    description: 'Додай записи у 20 різних днів місяця.',
    flavor: 'Тепер гроші не просто зникають. Вони залишають сліди.',
    target: 20,
    reward: 30,
    rarity: 'stone',
    rune: 'ᚢ',
  },
  {
    id: 'first-category',
    category: 'finance',
    title: 'ПЕРША КАТЕГОРІЯ',
    description: 'Додай категорію до фінансового запису.',
    flavor: 'Хаос отримав ім\'я. Це вже порядок.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᚦ',
  },
  {
    id: 'first-goal',
    category: 'finance',
    title: 'ПЕРШИЙ ЛІМІТ',
    description: 'Створи першу фінансову ціль.',
    flavor: 'Ціль без числа — лише мрія. Тепер число є.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚨ',
  },
  {
    id: 'first-pattern',
    category: 'finance',
    title: 'ПЕРШИЙ ПАТЕРН',
    description: 'Накопич 10 фінансових записів.',
    flavor: 'Ти не знайшов відповідь. Але знайшов напрям.',
    target: 10,
    reward: 25,
    rarity: 'stone',
    rune: 'ᚱ',
    hidden: true,
  },
  {
    id: 'daily-finance',
    category: 'finance',
    title: 'ЦІНА ДНЯ',
    description: 'Додай записи у 3 різних дні поспіль.',
    flavor: 'Три дні — і звичка починає жити.',
    target: 3,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚲ',
  },

  // ── КВЕСТИ / СПРИНТИ (10) ──────────────────────────────────────────────────
  {
    id: 'first-quest',
    category: 'sprint',
    title: 'ПЕРША ОБІТНИЦЯ',
    description: 'Створи перший квест або спринт.',
    flavor: 'Слова стали наміром. Небезпечно.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᚷ',
  },
  {
    id: 'first-step',
    category: 'sprint',
    title: 'ПЕРШИЙ КРОК',
    description: 'Виконай першу задачу.',
    flavor: 'Рух почався. Це вже більше, ніж план.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᚹ',
  },
  {
    id: 'three-steps',
    category: 'sprint',
    title: 'ТРИ КРОКИ',
    description: 'Виконай 3 задачі.',
    flavor: 'Три кроки — і шлях вже не здається довгим.',
    target: 3,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚺ',
  },
  {
    id: 'ten-steps',
    category: 'sprint',
    title: 'ДЕСЯТЬ КРОКІВ',
    description: 'Виконай 10 задач.',
    flavor: 'Десять — і ти вже не той, хто починав.',
    target: 10,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚾ',
  },
  {
    id: 'completed-path',
    category: 'sprint',
    title: 'ЗАВЕРШЕНИЙ ШЛЯХ',
    description: 'Заверши перший квест або спринт.',
    flavor: 'Не ідеально. Але завершено. Це рідкісніше.',
    target: 1,
    reward: 25,
    rarity: 'stone',
    rune: 'ᛁ',
  },
  {
    id: 'seven-days-fire',
    category: 'sprint',
    title: 'СІМ ДНІВ ВОГНЮ',
    description: 'Виконуй задачі 7 днів поспіль.',
    flavor: 'Воля — це не вибух. Це повторення.',
    target: 7,
    reward: 30,
    rarity: 'root',
    rune: 'ᛃ',
  },
  {
    id: 'return-after-fail',
    category: 'sprint',
    title: 'ПОВЕРНЕННЯ',
    description: 'Виконай задачу в простроченому квесті.',
    flavor: 'Провал не страшний. Страшна втеча.',
    target: 1,
    reward: 30,
    rarity: 'root',
    rune: 'ᛇ',
    hidden: true,
  },
  {
    id: 'three-day-chain',
    category: 'sprint',
    title: 'НЕ ЗЛАМАНИЙ ЛАНЦЮГ',
    description: 'Виконай задачі 3 дні поспіль.',
    flavor: 'Три дні — і ланцюг вже має вагу.',
    target: 3,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛈ',
  },
  {
    id: 'big-sprint',
    category: 'sprint',
    title: 'ВЕЛИКИЙ СПРИНТ',
    description: 'Виконай 5 задач в одному квесті або спринті.',
    flavor: 'Не одна задача. Ціла кампанія.',
    target: 5,
    reward: 30,
    rarity: 'stone',
    rune: 'ᛉ',
  },
  {
    id: 'three-quests',
    category: 'sprint',
    title: 'СВІДОК ВОЛІ',
    description: 'Заверши 3 квести або спринти.',
    flavor: 'Три рази — і це вже характер, а не збіг.',
    target: 3,
    reward: 50,
    rarity: 'root',
    rune: 'ᛊ',
  },

  // ── WATCHLIST / СМАК (10) ──────────────────────────────────────────────────
  {
    id: 'first-watchlist',
    category: 'watchlist',
    title: 'ПЕРША ПОЗНАЧКА',
    description: 'Додай перший item у Watchlist.',
    flavor: 'Смак теж потребує архіву.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛏ',
  },
  {
    id: 'first-movie',
    category: 'watchlist',
    title: 'ПЕРШИЙ ФІЛЬМ',
    description: 'Додай перший фільм у Watchlist.',
    flavor: 'Кіно починається з першого вибору.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛒ',
  },
  {
    id: 'first-series',
    category: 'watchlist',
    title: 'ПЕРШИЙ СЕРІАЛ',
    description: 'Додай перший серіал у Watchlist.',
    flavor: 'Серіал — це зобовʼязання. Ти зробив вибір.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛖ',
  },
  {
    id: 'first-anime',
    category: 'watchlist',
    title: 'ПЕРШЕ АНІМЕ',
    description: 'Додай перше аніме у Watchlist.',
    flavor: 'Інший формат. Інший погляд.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛗ',
  },
  {
    id: 'watched-completed',
    category: 'watchlist',
    title: 'ЗАВЕРШЕНО',
    description: 'Познач перший item як переглянутий.',
    flavor: 'Один намір став досвідом.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛚ',
  },
  {
    id: 'not-just-list',
    category: 'watchlist',
    title: 'СМАК ФОРМУЄТЬСЯ',
    description: 'Заверши перегляд 5 items.',
    flavor: 'Ти вже не пробуєш. Ти обираєш.',
    target: 5,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛜ',
  },
  {
    id: 'first-rating',
    category: 'watchlist',
    title: 'ПЕРША ОЦІНКА',
    description: 'Додай оцінку до item.',
    flavor: 'Оцінка — це позиція. Ти її маєш.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛞ',
  },
  {
    id: 'ten-watchlist',
    category: 'watchlist',
    title: 'ДЕСЯТЬ У СПИСКУ',
    description: 'Додай 10 items у Watchlist.',
    flavor: 'Список став архівом.',
    target: 10,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛟ',
  },
  {
    id: 'taste-archive',
    category: 'watchlist',
    title: 'АРХІВ СМАКУ',
    description: 'Заверши перегляд 10 items.',
    flavor: 'Тепер це вже не випадковий список.',
    target: 10,
    reward: 30,
    rarity: 'stone',
    rune: 'ᚠ',
  },
  {
    id: 'taste-variety',
    category: 'watchlist',
    title: 'СМАК МАЄ ФОРМУ',
    description: 'Додай items у всіх 3 категоріях: фільм, серіал, аніме.',
    flavor: 'Різноманіття — це не розпорошення. Це широта.',
    target: 3,
    reward: 30,
    rarity: 'stone',
    rune: 'ᚢ',
  },
]

export const ACHIEVEMENT_MAX_SCORE = ACHIEVEMENT_DEFS.reduce((s, a) => s + a.reward, 0)

export const ACHIEVEMENT_BY_ID: Record<string, AchievementDef> =
  Object.fromEntries(ACHIEVEMENT_DEFS.map(a => [a.id, a]))

/** Per-achievement badge — public/achivement/badges/[category]/[id].webp */
export const ACHIEVEMENT_BADGE: Record<string, string> =
  Object.fromEntries(ACHIEVEMENT_DEFS.map(a => [a.id, `/achivement/badges/${a.category}/${a.id}.webp`]))

// ── Branch node positions (% of canvas) ────────────────────────────────────
// All 5 category-well/[cat].png renders share the same branch template —
// only the medallion icons differ — so the medallion sockets sit at the
// same coordinates in every image (measured against the artwork).
// The branch art has 6 sockets total; only 5 are used as achievement nodes
// (the second-from-top socket is left as unclaimed decoration) to keep the
// map to 5 milestones per category.
// Order is root (bottom, easiest) → tip (top, hardest), matching how the
// tree grows: foundational achievements near the ground, the pinnacle near
// the crown.

const BRANCH_NODE_POS: { x: number; y: number }[] = [
  { x: 53.3, y: 76.8 }, // root — bottom
  { x: 45, y: 66 },
  { x: 53.6, y: 55 },
  { x: 45.3, y: 43.6 },
  { x: 54.5, y: 32.4 }, // tip — top
]

const BRANCH_IDS: Record<AchievementCategory, string[]> = {
  memory:    ['first-memory', 'past-memory', 'ten-memories', 'month-memory', 'archive-25'],
  spaces:    ['first-space', 'space-with-profile', 'living-space', 'five-spaces', 'life-map'],
  finance:   ['first-transaction', 'first-category', 'first-goal', 'first-pattern', 'month-watched'],
  sprint:    ['first-quest', 'three-steps', 'three-day-chain', 'ten-steps', 'return-after-fail'],
  watchlist: ['first-watchlist', 'first-series', 'watched-completed', 'not-just-list', 'taste-archive'],
}

export const TREE_NODES: Record<string, { id: string; x: number; y: number }[]> =
  Object.fromEntries(
    (Object.entries(BRANCH_IDS) as [AchievementCategory, string[]][]).map(([cat, ids]) => [
      cat,
      ids.map((id, i) => ({ id, ...BRANCH_NODE_POS[i] })),
    ]),
  )

// Linear chain: root → ... → tip
const BRANCH_CHAIN: [number, number][] = [[0,1],[1,2],[2,3],[3,4]]

export const TREE_CONNECTIONS: Record<string, [number, number][]> = {
  memory:   BRANCH_CHAIN,
  spaces:   BRANCH_CHAIN,
  finance:  BRANCH_CHAIN,
  sprint:   BRANCH_CHAIN,
  watchlist:BRANCH_CHAIN,
}
