import type { AchievementDef } from './types'

export const ACHIEVEMENT_DEFS: AchievementDef[] = [
  // ── ПАМʼЯТЬ (10) ───────────────────────────────────────────────────────────
  {
    id: 'first-memory',
    category: 'memory',
    title: 'ПЕРШИЙ СПОГАД',
    description: 'Додай свій перший спогад.',
    flavor: 'Ти залишив перший слід у криниці.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᚠ',
  },
  {
    id: 'memory-with-photo',
    category: 'memory',
    title: 'СПОГАД З ОБРАЗОМ',
    description: 'Додай спогад із фото.',
    flavor: 'Не все треба пояснювати словами.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚢ',
  },
  {
    id: 'past-memory',
    category: 'memory',
    title: 'ПОВЕРНЕНЕ МИНУЛЕ',
    description: 'Додай спогад із датою в минулому.',
    flavor: 'Те, що минуло, ще не зникло.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚦ',
  },
  {
    id: 'three-memories',
    category: 'memory',
    title: 'ТРИ СПОГАДИ',
    description: 'Додай 3 спогади.',
    flavor: 'Три — це вже не випадковість.',
    target: 3,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚨ',
  },
  {
    id: 'ten-memories',
    category: 'memory',
    title: 'ДЕСЯТЬ СЛІДІВ',
    description: 'Додай 10 спогадів.',
    flavor: 'Криниця наповнюється.',
    target: 10,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚱ',
  },
  {
    id: 'seven-days-memory',
    category: 'memory',
    title: 'СІМ ДНІВ ПАМʼЯТІ',
    description: 'Додай спогади у 7 різних днів.',
    flavor: 'Памʼять не любить поспіх. Вона любить повернення.',
    target: 7,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚲ',
  },
  {
    id: 'month-memory',
    category: 'memory',
    title: 'МІСЯЦЬ НЕ ЗНИК',
    description: 'Додай спогади у 20 різних днів.',
    flavor: 'Місяць, що залишив сліди. Це рідкість.',
    target: 20,
    reward: 30,
    rarity: 'stone',
    rune: 'ᚷ',
  },
  {
    id: 'memory-in-space',
    category: 'memory',
    title: 'СПОГАД У ПРОСТОРІ',
    description: 'Привʼяжи спогад до простору.',
    flavor: 'Місце і момент. Тепер вони звʼязані.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚹ',
  },
  {
    id: 'memory-with-person',
    category: 'memory',
    title: 'СПОГАД З ЛЮДИНОЮ',
    description: 'Додай людину до спогаду.',
    flavor: 'Памʼять стає спільною — і тому сильнішою.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚺ',
  },
  {
    id: 'archive-25',
    category: 'memory',
    title: 'АРХІВ ПРОКИНУВСЯ',
    description: 'Створи 25 спогадів.',
    flavor: 'Криниця вже не порожня. Вона говорить.',
    target: 25,
    reward: 50,
    rarity: 'root',
    rune: 'ᚾ',
  },

  // ── ПРОСТОРИ (10) ──────────────────────────────────────────────────────────
  {
    id: 'first-space',
    category: 'spaces',
    title: 'ПЕРШИЙ ПРОСТІР',
    description: 'Створи свій перший простір.',
    flavor: 'У хаосу зʼявилась кімната.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛁ',
  },
  {
    id: 'space-with-profile',
    category: 'spaces',
    title: 'ОПИСАНИЙ ПРОСТІР',
    description: 'Заповни профіль простору (авто, дім, тварина або подорож).',
    flavor: 'Місце отримало характер. Тепер воно — не просто назва.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛃ',
  },
  {
    id: 'space-with-cover',
    category: 'spaces',
    title: 'ОБКЛАДИНКА МІСЦЯ',
    description: 'Додай обкладинку до простору.',
    flavor: 'Місце отримало своє обличчя. Тепер його не сплутаєш.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛇ',
  },
  {
    id: 'three-spaces',
    category: 'spaces',
    title: 'ТРИ ПРОСТОРИ',
    description: 'Створи 3 простори.',
    flavor: 'Твоя карта починає мати форму.',
    target: 3,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛈ',
  },
  {
    id: 'five-spaces',
    category: 'spaces',
    title: 'ПʼЯТЬ ПРОСТОРІВ',
    description: 'Створи 5 просторів.',
    flavor: 'Пʼять кімнат. Місце стало картою.',
    target: 5,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛉ',
  },
  {
    id: 'living-space',
    category: 'spaces',
    title: 'ЖИВИЙ ПРОСТІР',
    description: 'Додай 3 спогади в один простір.',
    flavor: 'Простір оживає, коли в ньому щось відбувається.',
    target: 3,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛊ',
  },
  {
    id: 'full-space',
    category: 'spaces',
    title: 'НАСЕЛЕНИЙ ПРОСТІР',
    description: 'Додай 10 спогадів в один простір.',
    flavor: 'Не місце для спогадів. Місце зі спогадами.',
    target: 10,
    reward: 30,
    rarity: 'stone',
    rune: 'ᛏ',
  },
  {
    id: 'first-auto',
    category: 'spaces',
    title: 'АВТОСЛІД',
    description: 'Створи простір типу «Авто».',
    flavor: 'Навіть машина має памʼять. І рахунки.',
    target: 1,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛒ',
    hidden: true,
  },
  {
    id: 'first-home',
    category: 'spaces',
    title: 'ДІМ МАЄ ПАМʼЯТЬ',
    description: 'Створи простір типу «Дім».',
    flavor: 'Дім — це не адреса. Це те, що лишається.',
    target: 1,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛖ',
    hidden: true,
  },
  {
    id: 'life-map',
    category: 'spaces',
    title: 'КАРТА ЖИТТЯ',
    description: 'Створи простори щонайменше 5 різних типів.',
    flavor: 'Ти не просто організував. Ти намалював карту.',
    target: 5,
    reward: 50,
    rarity: 'root',
    rune: 'ᛗ',
  },

  // ── ФІНАНСИ (10) ───────────────────────────────────────────────────────────
  {
    id: 'first-transaction',
    category: 'finance',
    title: 'ПЕРША МОНЕТА',
    description: 'Додай перший фінансовий запис.',
    flavor: 'Одна монета — теж початок криниці.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛚ',
  },
  {
    id: 'seven-records',
    category: 'finance',
    title: 'СІМ ЗАПИСІВ',
    description: 'Додай 7 фінансових записів.',
    flavor: 'Патерни зʼявляються там, де є сліди.',
    target: 7,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛜ',
  },
  {
    id: 'ten-records',
    category: 'finance',
    title: 'ДЕСЯТЬ МОНЕТ',
    description: 'Додай 10 фінансових записів.',
    flavor: 'Десять слідів — і туман вже не такий густий.',
    target: 10,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛞ',
  },
  {
    id: 'no-fog-day',
    category: 'finance',
    title: 'ДЕНЬ БЕЗ ТУМАНУ',
    description: 'Запиши витрати за один день.',
    flavor: 'День став видимим.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛟ',
  },
  {
    id: 'week-watched',
    category: 'finance',
    title: 'ТИЖДЕНЬ ПІД НАГЛЯДОМ',
    description: 'Додай записи у 7 різних днів.',
    flavor: 'Сім днів без туману. Ти вже бачиш.',
    target: 7,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚠ',
  },
  {
    id: 'month-watched',
    category: 'finance',
    title: 'МІСЯЦЬ ПІД НАГЛЯДОМ',
    description: 'Додай записи у 20 різних днів місяця.',
    flavor: 'Тепер гроші не просто зникають. Вони залишають сліди.',
    target: 20,
    reward: 30,
    rarity: 'stone',
    rune: 'ᚢ',
  },
  {
    id: 'first-category',
    category: 'finance',
    title: 'ПЕРША КАТЕГОРІЯ',
    description: 'Додай категорію до фінансового запису.',
    flavor: 'Хаос отримав ім\'я. Це вже порядок.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᚦ',
  },
  {
    id: 'first-goal',
    category: 'finance',
    title: 'ПЕРШИЙ ЛІМІТ',
    description: 'Створи першу фінансову ціль.',
    flavor: 'Ціль без числа — лише мрія. Тепер число є.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚨ',
  },
  {
    id: 'first-pattern',
    category: 'finance',
    title: 'ПЕРШИЙ ПАТЕРН',
    description: 'Накопич 10 фінансових записів.',
    flavor: 'Ти не знайшов відповідь. Але знайшов напрям.',
    target: 10,
    reward: 25,
    rarity: 'stone',
    rune: 'ᚱ',
    hidden: true,
  },
  {
    id: 'daily-finance',
    category: 'finance',
    title: 'ЦІНА ДНЯ',
    description: 'Додай записи у 3 різних дні поспіль.',
    flavor: 'Три дні — і звичка починає жити.',
    target: 3,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚲ',
  },

  // ── КВЕСТИ / СПРИНТИ (10) ──────────────────────────────────────────────────
  {
    id: 'first-quest',
    category: 'sprint',
    title: 'ПЕРША ОБІТНИЦЯ',
    description: 'Створи перший квест або спринт.',
    flavor: 'Слова стали наміром. Небезпечно.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᚷ',
  },
  {
    id: 'first-step',
    category: 'sprint',
    title: 'ПЕРШИЙ КРОК',
    description: 'Виконай першу задачу.',
    flavor: 'Рух почався. Це вже більше, ніж план.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᚹ',
  },
  {
    id: 'three-steps',
    category: 'sprint',
    title: 'ТРИ КРОКИ',
    description: 'Виконай 3 задачі.',
    flavor: 'Три кроки — і шлях вже не здається довгим.',
    target: 3,
    reward: 15,
    rarity: 'spark',
    rune: 'ᚺ',
  },
  {
    id: 'ten-steps',
    category: 'sprint',
    title: 'ДЕСЯТЬ КРОКІВ',
    description: 'Виконай 10 задач.',
    flavor: 'Десять — і ти вже не той, хто починав.',
    target: 10,
    reward: 20,
    rarity: 'rune',
    rune: 'ᚾ',
  },
  {
    id: 'completed-path',
    category: 'sprint',
    title: 'ЗАВЕРШЕНИЙ ШЛЯХ',
    description: 'Заверши перший квест або спринт.',
    flavor: 'Не ідеально. Але завершено. Це рідкісніше.',
    target: 1,
    reward: 25,
    rarity: 'stone',
    rune: 'ᛁ',
  },
  {
    id: 'seven-days-fire',
    category: 'sprint',
    title: 'СІМ ДНІВ ВОГНЮ',
    description: 'Виконуй задачі 7 днів поспіль.',
    flavor: 'Воля — це не вибух. Це повторення.',
    target: 7,
    reward: 30,
    rarity: 'root',
    rune: 'ᛃ',
  },
  {
    id: 'return-after-fail',
    category: 'sprint',
    title: 'ПОВЕРНЕННЯ',
    description: 'Виконай задачу в простроченому квесті.',
    flavor: 'Провал не страшний. Страшна втеча.',
    target: 1,
    reward: 30,
    rarity: 'root',
    rune: 'ᛇ',
    hidden: true,
  },
  {
    id: 'three-day-chain',
    category: 'sprint',
    title: 'НЕ ЗЛАМАНИЙ ЛАНЦЮГ',
    description: 'Виконай задачі 3 дні поспіль.',
    flavor: 'Три дні — і ланцюг вже має вагу.',
    target: 3,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛈ',
  },
  {
    id: 'big-sprint',
    category: 'sprint',
    title: 'ВЕЛИКИЙ СПРИНТ',
    description: 'Виконай 5 задач в одному квесті або спринті.',
    flavor: 'Не одна задача. Ціла кампанія.',
    target: 5,
    reward: 30,
    rarity: 'stone',
    rune: 'ᛉ',
  },
  {
    id: 'three-quests',
    category: 'sprint',
    title: 'СВІДОК ВОЛІ',
    description: 'Заверши 3 квести або спринти.',
    flavor: 'Три рази — і це вже характер, а не збіг.',
    target: 3,
    reward: 50,
    rarity: 'root',
    rune: 'ᛊ',
  },

  // ── WATCHLIST / СМАК (10) ──────────────────────────────────────────────────
  {
    id: 'first-watchlist',
    category: 'watchlist',
    title: 'ПЕРША ПОЗНАЧКА',
    description: 'Додай перший item у Watchlist.',
    flavor: 'Смак теж потребує архіву.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛏ',
  },
  {
    id: 'first-movie',
    category: 'watchlist',
    title: 'ПЕРШИЙ ФІЛЬМ',
    description: 'Додай перший фільм у Watchlist.',
    flavor: 'Кіно починається з першого вибору.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛒ',
  },
  {
    id: 'first-series',
    category: 'watchlist',
    title: 'ПЕРШИЙ СЕРІАЛ',
    description: 'Додай перший серіал у Watchlist.',
    flavor: 'Серіал — це зобовʼязання. Ти зробив вибір.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛖ',
  },
  {
    id: 'first-anime',
    category: 'watchlist',
    title: 'ПЕРШЕ АНІМЕ',
    description: 'Додай перше аніме у Watchlist.',
    flavor: 'Інший формат. Інший погляд.',
    target: 1,
    reward: 10,
    rarity: 'spark',
    rune: 'ᛗ',
  },
  {
    id: 'watched-completed',
    category: 'watchlist',
    title: 'ЗАВЕРШЕНО',
    description: 'Познач перший item як переглянутий.',
    flavor: 'Один намір став досвідом.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛚ',
  },
  {
    id: 'not-just-list',
    category: 'watchlist',
    title: 'НЕ ПРОСТО СПИСОК',
    description: 'Додай нотатку до завершеного item.',
    flavor: 'Ти не просто переглянув. Ти сформулював.',
    target: 1,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛜ',
  },
  {
    id: 'first-rating',
    category: 'watchlist',
    title: 'ПЕРША ОЦІНКА',
    description: 'Додай оцінку до item.',
    flavor: 'Оцінка — це позиція. Ти її маєш.',
    target: 1,
    reward: 15,
    rarity: 'spark',
    rune: 'ᛞ',
  },
  {
    id: 'ten-watchlist',
    category: 'watchlist',
    title: 'ДЕСЯТЬ У СПИСКУ',
    description: 'Додай 10 items у Watchlist.',
    flavor: 'Список став архівом.',
    target: 10,
    reward: 20,
    rarity: 'rune',
    rune: 'ᛟ',
  },
  {
    id: 'taste-archive',
    category: 'watchlist',
    title: 'АРХІВ СМАКУ',
    description: 'Заверши перегляд 10 items.',
    flavor: 'Тепер це вже не випадковий список.',
    target: 10,
    reward: 30,
    rarity: 'stone',
    rune: 'ᚠ',
  },
  {
    id: 'taste-variety',
    category: 'watchlist',
    title: 'СМАК МАЄ ФОРМУ',
    description: 'Додай items у всіх 3 категоріях: фільм, серіал, аніме.',
    flavor: 'Різноманіття — це не розпорошення. Це широта.',
    target: 3,
    reward: 30,
    rarity: 'stone',
    rune: 'ᚢ',
  },
]

export const ACHIEVEMENT_MAX_SCORE = ACHIEVEMENT_DEFS.reduce((s, a) => s + a.reward, 0)

export const ACHIEVEMENT_BY_ID: Record<string, AchievementDef> =
  Object.fromEntries(ACHIEVEMENT_DEFS.map(a => [a.id, a]))

// ── Tree node positions (% of canvas) ──────────────────────────────────────
// Each category shows 10 nodes. "all" tab shows 9 key nodes across categories.
// Layout: 5-level tree with 2 nodes per level (+ 1 crown, 1 root)
// Level 1 (crown):  (50, 7)
// Level 2:          (25, 20) / (75, 20)
// Level 3:          (15, 36) / (85, 36)
// Level 4:          (30, 55) / (70, 55)
// Level 5:          (20, 66) / (90, 66)
// Root:             (50, 90)

export const TREE_NODES: Record<string, { id: string; x: number; y: number }[]> = {
  all: [
    { id: 'first-memory',      x: 50, y: 10 },
    { id: 'first-space',       x: 25, y: 32 },
    { id: 'first-transaction', x: 75, y: 32 },
    { id: 'first-quest',       x: 25, y: 57 },
    { id: 'first-watchlist',   x: 75, y: 57 },
    { id: 'seven-days-memory', x: 25, y: 82 },
    { id: 'life-map',          x: 75, y: 82 },
  ],
  memory: [
    { id: 'first-memory',      x: 50, y: 10 },
    { id: 'memory-with-photo', x: 25, y: 32 },
    { id: 'past-memory',       x: 75, y: 32 },
    { id: 'three-memories',    x: 25, y: 57 },
    { id: 'ten-memories',      x: 75, y: 57 },
    { id: 'seven-days-memory', x: 25, y: 82 },
    { id: 'archive-25',        x: 75, y: 82 },
  ],
  spaces: [
    { id: 'first-space',        x: 50, y: 10 },
    { id: 'space-with-cover',   x: 25, y: 32 },
    { id: 'space-with-profile', x: 75, y: 32 },
    { id: 'three-spaces',       x: 25, y: 57 },
    { id: 'living-space',       x: 75, y: 57 },
    { id: 'first-auto',         x: 25, y: 82 },
    { id: 'life-map',           x: 75, y: 82 },
  ],
  finance: [
    { id: 'first-transaction', x: 50, y: 10 },
    { id: 'no-fog-day',        x: 25, y: 32 },
    { id: 'first-category',    x: 75, y: 32 },
    { id: 'seven-records',     x: 25, y: 57 },
    { id: 'first-goal',        x: 75, y: 57 },
    { id: 'daily-finance',     x: 25, y: 82 },
    { id: 'first-pattern',     x: 75, y: 82 },
  ],
  sprint: [
    { id: 'first-quest',       x: 50, y: 10 },
    { id: 'first-step',        x: 25, y: 32 },
    { id: 'three-steps',       x: 75, y: 32 },
    { id: 'completed-path',    x: 25, y: 57 },
    { id: 'three-day-chain',   x: 75, y: 57 },
    { id: 'seven-days-fire',   x: 25, y: 82 },
    { id: 'return-after-fail', x: 75, y: 82 },
  ],
  watchlist: [
    { id: 'first-watchlist',   x: 50, y: 10 },
    { id: 'first-movie',       x: 25, y: 32 },
    { id: 'first-series',      x: 75, y: 32 },
    { id: 'first-anime',       x: 25, y: 57 },
    { id: 'watched-completed', x: 75, y: 57 },
    { id: 'ten-watchlist',     x: 25, y: 82 },
    { id: 'taste-archive',     x: 75, y: 82 },
  ],
}

// Clean binary tree — no cross-connections, lines follow branches naturally
const BRANCH_7: [number, number][] = [
  [0,1],[0,2],
  [1,3],[2,4],
  [3,5],[4,6],
]

export const TREE_CONNECTIONS: Record<string, [number, number][]> = {
  all:      BRANCH_7,
  memory:   BRANCH_7,
  spaces:   BRANCH_7,
  finance:  BRANCH_7,
  sprint:   BRANCH_7,
  watchlist:BRANCH_7,
}
